### ISSUE TITLE
Help creating a pull request:  Updating Fee info on the FAQ

### ISSUE THREAD

**Issue by ifarnung** [bisq-network/bisq-website#246]
Current old outdated fee information:
"Trading fees
Offer makers pay 0.1% of the trade amount, and offer takers pay 0.3% of the trade amount. The minimum in both cases is 0.00005 BTC to avoid dust limits. Fees paid with BSQ can be as much as 90% lower."

Based on info received from m52go:
![fee-increases-cycle-4](https://user-images.githubusercontent.com/55181240/64929191-8058b000-d82b-11e9-9f6c-6f535a51d815.png)
Proposed update:

"Trading fees
Offer makers pay 0.2% of the trade amount, and offer takers pay 0.6% of the trade amount. The minimum in both cases is 0.00005 BTC to avoid dust limits. When fees are paid with BSQ, offer makers pay 0.13% of the trade amount, and offer takers pay 0.38% of the trade amount."

**Comment by wiz** [comment]
Fixed in #245

**Comment by m52go** [comment]
@wiz this issue is for the FAQ section of the website, whereas 245 was for the blog post. This issue is still relevant.

**Comment by wiz** [comment]
Oh, right. How about we make a text table there then?

**Comment by m52go** [comment]
Yeah a table makes sense. Then it can simply be:

```
Trading fees are payable in BTC or in BSQ.

<table>

The minimum trading fee is 0.00005 BTC to avoid dust limits. Trading fees are DAO parameters, and can fluctuate with DAO voting.
```

**Comment by wiz** [comment]
Feel free to assign this to me, but I might not get to it for a few days

**Comment by m52go** [comment]
I can knock it out...unless you would like to, @ifarnung. Thanks for raising this point regardless.

**Comment by m52go** [comment]
Closing as complete.
